### ISSUE TITLE
user specific settings - spocr.json

### ISSUE THREAD

**Issue by p-i-p** [nuetzliches/spocr#38]
Allow a developer to generate a user specific spocr.json so that certain settings can be changed based on development environment. 
(Developer should add this file to gitignore)

**Comment by 7schmiede** [comment]
Please install newest Version (1.1.1).
Now you can update your global config with
> spocr config

You will be asked for UserId, please enter something like "pip" and save the config.
In your Project directory you can add a file, named as "spocr.user.pip.json".
In this File, you can overwrite your user specific settings, eg:
`{
  "Project": {
    "DataBase": {
      "ConnectionString": "Server=..."
    }
  }
}`
