### ISSUE TITLE
Create meaningful user output (e.g. like the Angular CLI)

### ISSUE THREAD

**Issue by fen89** [nuetzliches/spocr#51]
**Is your feature request related to a problem? Please describe.**
It would be really nice if spocr uses the `--dry-run` flag more in depth e.g. like the angular cli in comparison to print out some nice stuff to the user.

**Describe the solution you'd like**
More output on certain actions to the user. I tried something like the following (heavily inspired by the angular cli - full of bugs, as this is a quick and dirty demo with demo data all the way from sql to spocr):

![grafik](https://user-images.githubusercontent.com/4036376/67339096-cd1a5f80-f52a-11e9-9f71-05b903639e4d.png)

**Comment by 7schmiede** [comment]
solved with version 1.2
